name = "amalfimedia"
main = "./src/worker.js"
compatibility_date = "2026-05-12"
workers_dev = true
preview_urls = true

routes = [
  { pattern = "amalfi.media/*", zone_name = "amalfi.media" },
  { pattern = "www.amalfi.media/*", zone_name = "amalfi.media" }
]

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true
html_handling = "auto-trailing-slash"
